language: python
cache: pip

python:
    - "2.7"

# install jupyter and get reveal.js as we will need it to build the website
# from Travis
install:
    - pip install jupyter
    - wget https://github.com/hakimel/reveal.js/archive/3.5.0.zip
    - unzip 3.5.0.zip
    - mv reveal.js-3.5.0 reveal.js

script:
    - jupyter nbconvert presentation_julia.ipynb --to slides --reveal-prefix=reveal.js --SlidesExporter.reveal_theme=serif --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=none

after_success: |
    git checkout --orphan gh-pages
    git rm -rf --cached .
    mv presentation_julia.slides.html index.html
    git add -f --ignore-errors index.html figs reveal.js
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    
